services:
  postgres:
    image: postgres:16.0-alpine
    healthcheck:
      test: pg_isready
      interval: 3s
      timeout: 3s
      retries: 3
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    env_file: deploy.env
  backend:
    build: .
    depends_on:
      postgres:
          condition: service_healthy
    ports:
      - "8080:5000"
    env_file: deploy.env
volumes:
  data: {}